# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

#ruby encoding：utf-8

Menubar.create(menu_id: 'MENU01', menu_name: '系統參數設定', parent_menu_id: '', menu_sn: 100)
Menubar.create(menu_id: 'MENU0101', menu_name: '車輛資料設定作業', parent_menu_id: 'MENU01', menu_sn: 101)
Menubar.create(menu_id: 'MENU0102', menu_name: 'EMAIL內容設定', parent_menu_id: 'MENU01', menu_sn: 102)
Menubar.create(menu_id: 'MENU0103', menu_name: '倉庫資料管理', parent_menu_id: 'MENU01', menu_sn: 103)
Menubar.create(menu_id: 'MENU0104', menu_name: '架位儲位管理', parent_menu_id: 'MENU01', menu_sn: 104)
Menubar.create(menu_id: 'MENU0105', menu_name: '片語設定', parent_menu_id: 'MENU01', menu_sn: 105)
Menubar.create(menu_id: 'MENU0106', menu_name: '報表檔設定', parent_menu_id: 'MENU01', menu_sn: 106)
Menubar.create(menu_id: 'MENU0107', menu_name: '基本費率設定', parent_menu_id: 'MENU01', menu_sn: 107)
Menubar.create(menu_id: 'MENU0108', menu_name: '代碼設定', parent_menu_id: 'MENU01', menu_sn: 108)
Menubar.create(menu_id: 'MENU0109', menu_name: '自動排程維護', parent_menu_id: 'MENU01', menu_sn: 109)
Menubar.create(menu_id: 'MENU0110', menu_name: '多語系資料維護', parent_menu_id: 'MENU01', menu_sn: 110)
Menubar.create(menu_id: 'MENU0111', menu_name: '多語系-訊息資料維護', parent_menu_id: 'MENU01', menu_sn: 111)
Menubar.create(menu_id: 'MENU0112', menu_name: '程式資料維護', parent_menu_id: 'MENU01', menu_sn: 112)
Menubar.create(menu_id: 'MENU0113', menu_name: '選單資料維護', parent_menu_id: 'MENU01', menu_sn: 113, program_url: '/menubars')
Menubar.create(menu_id: 'MENU0114', menu_name: '行事曆設定', parent_menu_id: 'MENU01', menu_sn: 114)
Menubar.create(menu_id: 'MENU0115', menu_name: '檢查系統Log', parent_menu_id: 'MENU01', menu_sn: 115)
Menubar.create(menu_id: 'MENU02', menu_name: '系統權限設定', parent_menu_id: '', menu_sn: 200)
Menubar.create(menu_id: 'MENU0201', menu_name: '員工資料設定   ', parent_menu_id: 'MENU02', menu_sn: 201)
Menubar.create(menu_id: 'MENU0202', menu_name: '群組資料維護', parent_menu_id: 'MENU02', menu_sn: 202)
Menubar.create(menu_id: 'MENU0203', menu_name: '群組－程式控制設定', parent_menu_id: 'MENU02', menu_sn: 203)
Menubar.create(menu_id: 'MENU0204', menu_name: '使用者－群組權限設定', parent_menu_id: 'MENU02', menu_sn: 204)
Menubar.create(menu_id: 'MENU03', menu_name: '客戶資料設定', parent_menu_id: '', menu_sn: 300)
Menubar.create(menu_id: 'MENU0301', menu_name: '客戶公司資料管理作業', parent_menu_id: 'MENU03', menu_sn: 301)
Menubar.create(menu_id: 'MENU0302', menu_name: '客戶群組管理', parent_menu_id: 'MENU03', menu_sn: 302)
Menubar.create(menu_id: 'MENU0303', menu_name: '客戶帳單群組管理', parent_menu_id: 'MENU03', menu_sn: 303)
Menubar.create(menu_id: 'MENU04', menu_name: '客戶作業區', parent_menu_id: '', menu_sn: 400)
Menubar.create(menu_id: 'MENU0401', menu_name: '客戶工作通知單  ', parent_menu_id: 'MENU04', menu_sn: 401)
Menubar.create(menu_id: 'MENU0402', menu_name: '客戶工作通知單審核', parent_menu_id: 'MENU04', menu_sn: 402)
Menubar.create(menu_id: 'MENU0403', menu_name: '箱子/物件庫存查詢', parent_menu_id: 'MENU04', menu_sn: 403)
Menubar.create(menu_id: 'MENU0404', menu_name: '箱子/物件倉儲報表', parent_menu_id: 'MENU04', menu_sn: 404)
Menubar.create(menu_id: 'MENU0405', menu_name: '申請/異動作業', parent_menu_id: 'MENU04', menu_sn: 405)
Menubar.create(menu_id: 'MENU0406', menu_name: '客戶意見反映', parent_menu_id: 'MENU04', menu_sn: 406)
Menubar.create(menu_id: 'MENU0407', menu_name: '密碼變更', parent_menu_id: 'MENU04', menu_sn: 407)
Menubar.create(menu_id: 'MENU05', menu_name: '例行作業', parent_menu_id: '', menu_sn: 500)
Menubar.create(menu_id: 'MENU0501', menu_name: '工作通知單   ', parent_menu_id: 'MENU05', menu_sn: 501)
Menubar.create(menu_id: 'MENU0502', menu_name: '倉儲工作單', parent_menu_id: 'MENU05', menu_sn: 502)
Menubar.create(menu_id: 'MENU0503', menu_name: '倉儲工作核對明細報表', parent_menu_id: 'MENU05', menu_sn: 503)
Menubar.create(menu_id: 'MENU0504', menu_name: '工作單派車路線維護', parent_menu_id: 'MENU05', menu_sn: 504)
Menubar.create(menu_id: 'MENU0505', menu_name: '工作單上下架/稽核報表', parent_menu_id: 'MENU05', menu_sn: 505)
Menubar.create(menu_id: 'MENU0506', menu_name: '倉儲工作單上下架作業', parent_menu_id: 'MENU05', menu_sn: 506)
Menubar.create(menu_id: 'MENU0507', menu_name: '倉儲工作單稽核作業', parent_menu_id: 'MENU05', menu_sn: 507)
Menubar.create(menu_id: 'MENU0508', menu_name: '客戶意見反映回覆', parent_menu_id: 'MENU05', menu_sn: 508)
Menubar.create(menu_id: 'MENU0509', menu_name: '客戶申請/異動作業回覆', parent_menu_id: 'MENU05', menu_sn: 509)
Menubar.create(menu_id: 'MENU06', menu_name: '倉庫作業', parent_menu_id: '', menu_sn: 600)
Menubar.create(menu_id: 'MENU0601', menu_name: '移出單維護   ', parent_menu_id: 'MENU06', menu_sn: 601)
Menubar.create(menu_id: 'MENU0602', menu_name: '移出下架輸入', parent_menu_id: 'MENU06', menu_sn: 602)
Menubar.create(menu_id: 'MENU0603', menu_name: '移出稽核輸入', parent_menu_id: 'MENU06', menu_sn: 603)
Menubar.create(menu_id: 'MENU0604', menu_name: '移入單維護', parent_menu_id: 'MENU06', menu_sn: 604)
Menubar.create(menu_id: 'MENU0605', menu_name: '移入上架輸入', parent_menu_id: 'MENU06', menu_sn: 605)
Menubar.create(menu_id: 'MENU0606', menu_name: '移入稽核輸入', parent_menu_id: 'MENU06', menu_sn: 606)
Menubar.create(menu_id: 'MENU0607', menu_name: '上下架錯誤紀錄查詢', parent_menu_id: 'MENU06', menu_sn: 607)
Menubar.create(menu_id: 'MENU07', menu_name: '異常處理專區', parent_menu_id: '', menu_sn: 700)
Menubar.create(menu_id: 'MENU0701', menu_name: '結案工作單異動申請作業', parent_menu_id: 'MENU07', menu_sn: 701)
Menubar.create(menu_id: 'MENU0702', menu_name: '借出解領異動作業', parent_menu_id: 'MENU07', menu_sn: 702)
Menubar.create(menu_id: 'MENU0703', menu_name: '借出解領確認作業', parent_menu_id: 'MENU07', menu_sn: 703)
Menubar.create(menu_id: 'MENU08', menu_name: '報表專區', parent_menu_id: '', menu_sn: 800)
Menubar.create(menu_id: 'MENU0801', menu_name: '箱子/物件庫存查詢    ', parent_menu_id: 'MENU08', menu_sn: 801)
Menubar.create(menu_id: 'MENU0802', menu_name: '箱子/物件倉儲報表', parent_menu_id: 'MENU08', menu_sn: 802)
Menubar.create(menu_id: 'MENU0803', menu_name: '工作單箱/件日報表', parent_menu_id: 'MENU08', menu_sn: 803)
Menubar.create(menu_id: 'MENU0804', menu_name: '工作單箱/件統計表', parent_menu_id: 'MENU08', menu_sn: 804)
Menubar.create(menu_id: 'MENU0805', menu_name: '工作單未上下架稽核報表', parent_menu_id: 'MENU08', menu_sn: 805)
Menubar.create(menu_id: 'MENU0806', menu_name: '倉儲客戶月統計報表', parent_menu_id: 'MENU08', menu_sn: 806)
Menubar.create(menu_id: 'MENU0807', menu_name: '倉儲客戶各部門月統計報表', parent_menu_id: 'MENU08', menu_sn: 807)
Menubar.create(menu_id: 'MENU0808', menu_name: '箱子/物件庫存進出統計報表', parent_menu_id: 'MENU08', menu_sn: 808)
Menubar.create(menu_id: 'MENU0809', menu_name: '箱子/物件每日進出月報表(XLS輸出)', parent_menu_id: 'MENU08', menu_sn: 809)
Menubar.create(menu_id: 'MENU0810', menu_name: '每月通知單統計數量', parent_menu_id: 'MENU08', menu_sn: 810)
Menubar.create(menu_id: 'MENU0811', menu_name: '箱/件借出未回統計', parent_menu_id: 'MENU08', menu_sn: 811)
Menubar.create(menu_id: 'MENU0812', menu_name: '稽核報告', parent_menu_id: 'MENU08', menu_sn: 812)
Menubar.create(menu_id: 'MENU0813', menu_name: '委外倉儲收、送之箱/件統計', parent_menu_id: 'MENU08', menu_sn: 813)
Menubar.create(menu_id: 'MENU0814', menu_name: '箱件修改記錄查詢', parent_menu_id: 'MENU08', menu_sn: 814)
Menubar.create(menu_id: 'MENU0815', menu_name: '工作單即時資訊', parent_menu_id: 'MENU08', menu_sn: 815)
Menubar.create(menu_id: 'MENU0816', menu_name: '倉儲即時資訊', parent_menu_id: 'MENU08', menu_sn: 816)
Menubar.create(menu_id: 'MENU0817', menu_name: '箱/件借出統計排行報表', parent_menu_id: 'MENU08', menu_sn: 817)
Menubar.create(menu_id: 'MENU09', menu_name: '盤點作業', parent_menu_id: '', menu_sn: 900)
Menubar.create(menu_id: 'MENU0901', menu_name: '盤點單 ', parent_menu_id: 'MENU09', menu_sn: 901)
Menubar.create(menu_id: 'MENU0902', menu_name: '初盤作業', parent_menu_id: 'MENU09', menu_sn: 902)
Menubar.create(menu_id: 'MENU0903', menu_name: '複盤作業', parent_menu_id: 'MENU09', menu_sn: 903)
Menubar.create(menu_id: 'MENU10', menu_name: '結算作業', parent_menu_id: '', menu_sn: 1000)
Menubar.create(menu_id: 'MENU1001', menu_name: '往來日明細報表   ', parent_menu_id: 'MENU10', menu_sn: 1001)
Menubar.create(menu_id: 'MENU1002', menu_name: '往來日統計報表', parent_menu_id: 'MENU10', menu_sn: 1002)
Menubar.create(menu_id: 'MENU1003', menu_name: '往來月統計報表', parent_menu_id: 'MENU10', menu_sn: 1003)
Menubar.create(menu_id: 'MENU1004', menu_name: '結帳組別成本中心箱數統計', parent_menu_id: 'MENU10', menu_sn: 1004)
Menubar.create(menu_id: 'MENU11', menu_name: '條碼列印', parent_menu_id: '', menu_sn: 1100)
Menubar.create(menu_id: 'MENU1101', menu_name: '箱子自訂條碼列印 ', parent_menu_id: 'MENU11', menu_sn: 1101)
Menubar.create(menu_id: 'MENU1102', menu_name: '物件自訂條碼列印', parent_menu_id: 'MENU11', menu_sn: 1102)
Menubar.create(menu_id: 'MENU1103', menu_name: '封箱條號碼維護', parent_menu_id: 'MENU11', menu_sn: 1103)
Menubar.create(menu_id: 'MENU1104', menu_name: '儲位條碼列印', parent_menu_id: 'MENU11', menu_sn: 1104)
Menubar.create(menu_id: 'MENU1105', menu_name: '條碼列印記錄查詢', parent_menu_id: 'MENU11', menu_sn: 1105)
Menubar.create(menu_id: 'MENU12', menu_name: '稽核作業', parent_menu_id: '', menu_sn: 1200)
Menubar.create(menu_id: 'MENU1201', menu_name: '表A003存倉物品抽查記錄表', parent_menu_id: 'MENU12', menu_sn: 1201)
Menubar.create(menu_id: 'MENU1202', menu_name: '表A004倉庫表單抽查記錄表', parent_menu_id: 'MENU12', menu_sn: 1202)
Menubar.create(menu_id: 'MENU1203', menu_name: 'A005文件進倉記錄表', parent_menu_id: 'MENU12', menu_sn: 1203)
